server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training?serverTimezone=UTC
    username: root
    password: 4869
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.10.100
    port: 5672
    username: ltcyu
    password: 4869
logging:
  level:
    com.ltcyu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ltcyu.hotel.pojo